name: filcnaplo_premium
publish_to: "none"

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Filcnaplo main dep
  filcnaplo:
    path: ../filcnaplo/
  filcnaplo_kreta_api:
    path: ../filcnaplo_kreta_api/
  filcnaplo_mobile_ui:
    path: "../filcnaplo_mobile_ui/"

  provider: ^5.0.0
  flutter_feather_icons: ^2.0.0+1
  uni_links: ^0.5.1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
